// <auto-generated />
using FormUygulamasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormUygulamasi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922120438_IlIlceTablolari")]
    partial class IlIlceTablolari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FormUygulamasi.Models.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CariAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CariSoyadi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaVKN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("FormUygulamasi.Models.Il", b =>
                {
                    b.Property<int>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IlId");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("FormUygulamasi.Models.Ilce", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IlceId");

                    b.HasIndex("IlId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("FormUygulamasi.Models.Stok", b =>
                {
                    b.Property<int>("StokKodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KdvOrani")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<string>("StokAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StokKodu");

                    b.ToTable("Stoklar");
                });

            modelBuilder.Entity("FormUygulamasi.Models.Ilce", b =>
                {
                    b.HasOne("FormUygulamasi.Models.Il", "Il")
                        .WithMany("Ilceler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("FormUygulamasi.Models.Il", b =>
                {
                    b.Navigation("Ilceler");
                });
#pragma warning restore 612, 618
        }
    }
}
