// <auto-generated />
using FormUygulamasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormUygulamasi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720081721_StokTablosu")]
    partial class StokTablosu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FormUygulamasi.Models.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CariAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CariSoyadi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaVKN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("FormUygulamasi.Models.Stok", b =>
                {
                    b.Property<int>("StokKodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KdvOrani")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<string>("StokAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StokKodu");

                    b.ToTable("Stoklar");
                });
#pragma warning restore 612, 618
        }
    }
}
